name: 🚀 Deploy website to FTP Server Hostigator

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Deploy code
        run: lftp -c "set ftp:ssl-allow no; open -u ${{ secrets.ftp_user }},${{ secrets.ftp_password }} ftp://${{ secrets.ftp_host }}; mirror -R --ignore-time --parallel=10 -I 'node_modules' -I '.git' -I '.github' local/path/to/folder prod/classificados/"

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: prod/classificados/
